spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: H19931001521
    url: jdbc:mysql://127.0.0.1:3306/pw_ps?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

server:
  servlet:
    context-path: /personalShare
  port: 8080

#该配置用于数据库字段下划线与实体类属性驼峰互转
mybatis:
  configuration:
    map-underscore-to-camel-case: true

    #日志输出相关配置
    #logging:
    #  file:
    #    path: H:\data\logs\personalshare
    #  pattern:
#    level: info

token:
  cookieName: personalToken
  cookieSecrete: AHUMAN
  effectiveTime: 7200
  domain: pirateswang.cn
  exclude:
    urls:
      - /auth/
      - /article/
      - /doc

service:
  whiteListDomainList:
    - pirateswang.cn
    - www.pirateswang.cn
    - tomcatCluster


  #公钥路径
  userLoginRsaPublicKey: cert/Login_public_Rsa_key.txt
  #私钥路径
  userLoginRsaPrivateKey: cert/Login_private_Rsa_key.txt

